#! /usr/bin/env mulle-bash
# shellcheck shell=bash
#
#   Copyright (c) 2021 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = 'YES' -o "${MULLE_SEMVER_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION="1.0.2"

#
# Determine location of own libexec directory. Which is `src` in development
# and ../libexec when deployed.
#

if ! [ ${MULLE_SEMVER_LIBEXEC_DIR+x} ]
then
   r_get_libexec_dir "${MULLE_EXECUTABLE}" "mulle-semver" "mulle-semver-parse.sh"
   MULLE_SEMVER_LIBEXEC_DIR="${RVAL}"
fi

set +u


semver::print_flags()
{
   options_technical_flags_usage "       : "
}


semver::usage()
{
   [ $# -ne 0 ] && log_error "$*"

   cat <<EOF >&2
Usage:
   ${MULLE_USAGE_NAME} [flags] <command> [options]

   Parse and compare semver strings and evaluate semver expressions.

Commands:
   alphanumeric-compare <alphanumeric> <alphanumeric>
   compare              <semver> <semver>
   qualify              <qualifier> <version>
   qualifier-type       <qualifier>
   numeric-compare      <number> <number>
   parse                <strings>*
   search               <qualifier> <version>*

   (use <command> --help for usage information)
Flags:
EOF
   semver::print_flags | LC_ALL=C sort >&2

   exit 1
}


semver::main()
{
   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            semver::usage
         ;;

         -*)
            "semver::usage" "Unknown option \"$1\""
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}" && set -x

   # ui! ???
   shell_disable_glob

   local cmd="$1"
   [ $# -eq 0 ] || shift

   case "${cmd}" in
      'parse'|'numeric-compare'|'alphanumeric-compare'|'compare')
         # when you rename command, search for '***' and rename as well
         # shellcheck source=src/mulle-semver-parse.sh
         . "${MULLE_SEMVER_LIBEXEC_DIR}/mulle-semver-parse.sh" || _internal_fail "mulle-semver-parse.sh could not be loaded from \"${MULLE_SEMVER_LIBEXEC_DIR}\""

         semver::parse::${cmd//-/_}_main "$@"
      ;;

      'qualify'|'search'|'sort')
         # shellcheck source=src/mulle-semver-sort.sh
         . "${MULLE_SEMVER_LIBEXEC_DIR}/mulle-semver-${cmd}.sh"

         semver::${cmd}::main "$@"
      ;;

      'qualifier-type')
         # shellcheck source=src/mulle-semver-qualify.sh
         . "${MULLE_SEMVER_LIBEXEC_DIR}/mulle-semver-qualify.sh"

         semver::qualify::qualifier_type_main "$@"
      ;;


      'libexec-dir')
         printf "%s\n" "${MULLE_SEMVER_LIBEXEC_DIR}"
      ;;


      'version')
         printf "%s\n" "${MULLE_EXECUTABLE_VERSION}"
      ;;

      "")
         semver::usage
      ;;

      *)
         semver::usage "Unknown command \"${cmd}\""
      ;;
   esac
}


call_with_flags "semver::main" "${MULLE_SEMVER_FLAGS}" "$@"
