#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"


stacktrace()
{
   local i=1
   local line

   while line="`caller $i`"
   do
      printf "${C_CYAN}%b${C_RESET}\n" "$i: #${line}"
      ((i++))
   done
}

fail()
{
   echo "Unexpected " >&2
   stacktrace >&2
}


ASCENDING=60
SAME=0
DESCENDING=62


expect_rval()
{
   local rval="$1"
   local expect="$2"

   if [ "${rval}" != "${expect}" ]
   then
      echo "Expected $1 but got $2"
      exit 1
   fi
}


expect()
{
   local expect="$1"
   local rval="$2"

   if [ "${rval}" != "${expect}" ]
   then
      echo "Expected $1 but got $2"
      exit 1
   fi
}




main()
{
   MULLE_SEMVER_FLAGS="$@"

   _options_mini_main "$@"

   set -x
   ${MULLE_SEMVER} alphanumeric-compare -q abc abc
   expect ${SAME} $?

   ${MULLE_SEMVER} alphanumeric-compare -q abc cba
   expect ${ASCENDING} $?

   ${MULLE_SEMVER} alphanumeric-compare -q cba abc
   expect ${DESCENDING} $?

   ${MULLE_SEMVER} alphanumeric-compare -q ab abc
   expect ${ASCENDING} $?

   ${MULLE_SEMVER} alphanumeric-compare -q abc cb
   expect ${ASCENDING} $?

   ${MULLE_SEMVER} alphanumeric-compare -q cba c
   expect ${DESCENDING} $?

   ${MULLE_SEMVER} alphanumeric-compare -q "" ""
   expect 1 $?

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_SEMVER="${MULLE_SEMVER:-${PWD}/../../mulle-semver}"
}


init "$@"
main "$@"

