#! /bin/sh

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###
MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions libexec-dir`" || exit 1
export MULLE_BASHFUNCTIONS_LIBEXEC_DIR
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-boot.sh" || exit 1
. "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1
###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###   ###



fail()
{
   echo "Unexpected " >&2
   stacktrace >&2
}


ASCENDING=60
SAME=0
DESCENDING=62


expect()
{
   local expect="$1"
   local rval="$2"

   if [ "${rval}" != "${expect}" ]
   then
      echo "Expected $1 but got $2"
      exit 1
   fi
}




main()
{
   MULLE_SEMVER_FLAGS="$@"

   _options_mini_main "$@" && set -x

   ${MULLE_SEMVER} numeric-compare -q 0 0
   expect ${SAME} $?

   ${MULLE_SEMVER} numeric-compare -q 1 0
   expect ${DESCENDING} $?

   ${MULLE_SEMVER} numeric-compare -q 0 1
   expect ${ASCENDING} $?

   ${MULLE_SEMVER} numeric-compare -q 999999999999999 999999999999998
   expect ${DESCENDING} $?

   ${MULLE_SEMVER} -s --mulle-no-errors  numeric-compare 00 0
   expect 1 $?

   log_info "----- ALL PASSED -----"
}


init()
{
   MULLE_SEMVER="${MULLE_SEMVER:-${PWD}/../../mulle-semver}"
}


init "$@"
main "$@"

